version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend
    healthcheck:
      test: mongosh -u root -p root --quiet --eval="try { rs.status().ok } catch { rs.initiate().ok }"
      interval: 5s
      start_period: 5s
      retries: 2
    volumes:
      - mongodata:/data/db
    labels:
      com.docker.compose.env: "perftest"

  perftest:
    build:
      dockerfile: Dockerfile
      context: .
      target: perftest
      labels:
        com.docker.compose.env: "perftest"
    image: "mongodb-perftest"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGODB_URI: "mongodb://root:root@mongo:27017"
    networks:
      - backend
    labels:
      com.docker.compose.env: "perftest"

volumes:
  mongodata:
    name: "mongodata.perftest"
    labels:
      com.docker.compose.env: "perftest"

networks:
  backend:
    name: "backend.network.test"
    labels:
      com.docker.compose.env: "perftest"
